"""Registered radar sources and official presentation guides."""

from __future__ import annotations

from typing import Any

from .models import RadarSource

SOURCES = (
    RadarSource(
        "openrouter-models",
        "OpenRouter Models",
        "https://openrouter.ai/api/v1/models?output_modalities=all",
        "official",
        "token",
        "official_api",
        24,
        "json",
        ("openrouter.ai",),
    ),
    RadarSource(
        "groq-free-limits",
        "Groq Free Plan Limits",
        "https://console.groq.com/docs/rate-limits",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("console.groq.com",),
    ),
    RadarSource(
        "gemini-free-tier",
        "Gemini Developer API Pricing",
        "https://ai.google.dev/gemini-api/docs/pricing",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("ai.google.dev",),
    ),
    RadarSource(
        "cloudflare-workers-ai",
        "Cloudflare Workers AI Pricing",
        "https://developers.cloudflare.com/workers-ai/platform/pricing/",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("developers.cloudflare.com",),
    ),
    RadarSource(
        "zhipu-cogview-3-flash",
        "Zhipu AI CogView-3-Flash",
        "https://docs.bigmodel.cn/cn/guide/models/free/cogview-3-flash",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("docs.bigmodel.cn",),
    ),
    RadarSource(
        "huggingface-zerogpu",
        "Hugging Face ZeroGPU",
        "https://huggingface.co/docs/hub/main/spaces-zerogpu",
        "official",
        "gpu",
        "official_page",
        24,
        "html",
        ("huggingface.co",),
    ),
    RadarSource(
        "modal-pricing",
        "Modal Pricing",
        "https://modal.com/pricing",
        "official",
        "gpu",
        "official_page",
        24,
        "html",
        ("modal.com",),
    ),
    RadarSource(
        "runpod-gpu-pricing",
        "RunPod GPU Pricing",
        "https://www.runpod.io/gpu-instance/pricing",
        "official",
        "pricing",
        "official_page",
        24,
        "html",
        ("www.runpod.io", "runpod.io"),
    ),
    RadarSource(
        "lambda-gpu-pricing",
        "Lambda GPU Cloud Pricing",
        "https://lambda.ai/service/gpu-cloud",
        "official",
        "pricing",
        "official_page",
        24,
        "html",
        ("lambda.ai",),
    ),
    RadarSource(
        "vast-gpu-pricing",
        "Vast.ai Live GPU Pricing",
        "https://vast.ai/pricing",
        "official",
        "pricing",
        "official_page",
        24,
        "html",
        ("vast.ai",),
    ),
    RadarSource(
        "lightning-pricing",
        "Lightning AI Pricing",
        "https://lightning.ai/v1/billing/subscription/quote?orgId=&tier=Free",
        "official",
        "gpu",
        "official_page",
        24,
        "json",
        ("lightning.ai",),
    ),
    RadarSource(
        "kaggle-gpu",
        "Kaggle GPU Usage",
        "https://www.kaggle.com/api/i/cms.LegacyCmsService/GetPage?slug=docs%2Fefficient-gpu-usage&isEditing=false",
        "official",
        "gpu",
        "official_page",
        24,
        "json",
        ("www.kaggle.com", "kaggle.com"),
    ),
    RadarSource(
        "colab-faq",
        "Google Colab FAQ",
        "https://research.google.com/colaboratory/faq.html",
        "official",
        "gpu",
        "official_page",
        24,
        "html",
        ("research.google.com",),
    ),
    RadarSource(
        "sambanova-free-tier",
        "SambaNova Free Tier Limits",
        "https://docs.sambanova.ai/docs/en/models/rate-limits",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("docs.sambanova.ai",),
    ),
    RadarSource(
        "mistral-free-mode",
        "Mistral Studio Free Mode",
        "https://docs.mistral.ai/getting-started/quickstarts/studio/activate-and-generate-api-key",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("docs.mistral.ai",),
    ),
    RadarSource(
        "huggingface-inference-credits",
        "Hugging Face Inference Credits",
        "https://huggingface.co/docs/inference-providers/en/pricing",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("huggingface.co",),
    ),
    RadarSource(
        "siliconflow-free-models",
        "SiliconFlow Free Models",
        "https://docs.siliconflow.cn/cn/userguide/rate-limits/rate-limit-and-upgradation",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("docs.siliconflow.cn",),
    ),
    RadarSource(
        "alibaba-model-studio-trial",
        "Alibaba Model Studio New-user Quota",
        "https://help.aliyun.com/zh/model-studio/new-free-quota/",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("help.aliyun.com",),
    ),
    RadarSource(
        "cerebras-free-trial",
        "Cerebras Free Trial",
        "https://inference-docs.cerebras.ai/support/rate-limits",
        "official",
        "token",
        "official_page",
        24,
        "html",
        ("inference-docs.cerebras.ai",),
    ),
    RadarSource(
        "replicate-pricing",
        "Replicate Pricing",
        "https://replicate.com/pricing",
        "official",
        "pricing",
        "official_page",
        24,
        "html",
        ("replicate.com",),
    ),
    RadarSource(
        "baseten-pricing",
        "Baseten Pricing",
        "https://www.baseten.co/pricing/",
        "official",
        "pricing",
        "official_page",
        24,
        "html",
        ("www.baseten.co", "baseten.co"),
    ),
    RadarSource(
        "mnfst-free-llm-apis",
        "awesome-free-llm-apis",
        "https://raw.githubusercontent.com/mnfst/awesome-free-llm-apis/main/data.json",
        "CC0-1.0",
        "token",
        "community",
        168,
        "json",
        ("raw.githubusercontent.com",),
    ),
    RadarSource(
        "pydantic-genai-prices",
        "genai-prices",
        "https://raw.githubusercontent.com/pydantic/genai-prices/main/prices/data.json",
        "MIT",
        "pricing",
        "community",
        24,
        "json",
        ("raw.githubusercontent.com",),
    ),
)
SOURCE_BY_ID = {source.id: source for source in SOURCES}


OFFICIAL_GUIDES: dict[str, dict[str, Any]] = {
    "OpenRouter": {
        "benefit_summary": "每天共享 50 次免费请求，可直接调用带 :free 标记的模型；不是每个模型各 50 次。",
        "best_for": "快速试用不同厂商的文本、多模态和嵌入模型。",
        "action_label": "去创建 API Key",
        "action_url": "https://openrouter.ai/settings/keys",
        "usage_steps": [
            "注册或登录 OpenRouter。",
            "在 Keys 页面创建一个 API Key。",
            "选择带 :free 标记的模型，或使用 openrouter/free 路由。",
            "按 OpenAI 兼容接口发起请求，免费请求从共享日额度中扣除。",
        ],
        "caveats": [
            "50 次是免费模型共享日额度，不是每个模型分别计算。",
            "免费模型可能因上游容量临时不可用，购买额度后请求上限可能提高。",
        ],
    },
    "Groq": {
        "benefit_summary": "免费 API 按模型提供 RPM、RPD、TPM 和 TPD 限额，适合低延迟推理与开发测试。",
        "best_for": "需要高速文本生成、语音或开源模型 API 的开发测试。",
        "action_label": "去创建 API Key",
        "action_url": "https://console.groq.com/keys",
        "usage_steps": [
            "注册或登录 GroqCloud Console。",
            "在 API Keys 页面创建密钥。",
            "从免费计划限额表中选择适合的模型。",
            "使用官方 SDK 或 OpenAI 兼容接口调用，并在控制台查看用量。",
        ],
        "caveats": [
            "不同模型的每分钟、每日请求和 Token 限额不同。",
            "限额可能按组织和账号状态调整，以控制台显示为准。",
        ],
    },
    "Google Gemini": {
        "benefit_summary": "部分 Gemini 模型提供免费 API 层；可用模型和实际限额以 AI Studio 项目页面为准。",
        "best_for": "体验 Gemini 文本和多模态能力，或开发小流量原型。",
        "action_label": "打开 AI Studio",
        "action_url": "https://aistudio.google.com/apikey",
        "usage_steps": [
            "登录 Google AI Studio。",
            "创建或选择一个项目并生成 API Key。",
            "确认目标模型标有 Free Tier，并查看项目当前限额。",
            "使用 Gemini SDK 或 REST API 调用，在 AI Studio 监控用量。",
        ],
        "caveats": [
            "只有部分模型包含免费层，账号实际额度可能不同。",
            "官方地区政策未包含中国大陆，页面会默认过滤此项。",
        ],
    },
    "Cloudflare": {
        "benefit_summary": "Workers Free 计划每天赠送 10,000 Neurons，用于 Workers AI 模型推理。",
        "best_for": "把 AI 推理接入 Worker、边缘接口或轻量应用。",
        "action_label": "打开 Workers AI",
        "action_url": "https://dash.cloudflare.com/?to=/:account/ai/workers-ai",
        "usage_steps": [
            "注册或登录 Cloudflare Dashboard。",
            "进入 Workers AI，选择一个模型并创建调用。",
            "可以在控制台试运行，也可以通过 Worker、REST API 或 SDK 接入。",
            "用量从当日免费 Neurons 中扣除，并在 00:00 UTC 重置。",
        ],
        "caveats": [
            "Neurons 是按模型计算量计费的单位，不等于固定请求次数。",
            "不同模型每次推理消耗的 Neurons 不同。",
        ],
    },
    "Zhipu AI": {
        "benefit_summary": "CogView-3-Flash 提供官方免费的文生图 API；官方未公布固定日额度，以账号速率限制为准。",
        "best_for": "中文提示词的图片生成、原型验证和低成本 API 接入。",
        "action_label": "打开智谱 API 控制台",
        "action_url": "https://bigmodel.cn/usercenter/proj-mgmt/apikeys",
        "usage_steps": [
            "注册或登录智谱开放平台。",
            "在 API Keys 页面创建密钥。",
            "调用图像生成接口并选择 cogview-3-flash 模型。",
            "在控制台查看账号当前速率限制和使用情况。",
        ],
        "caveats": [
            "模型免费，但官方未公布固定每日额度。",
            "实际可用频率以账号显示的速率限制为准。",
        ],
    },
    "Hugging Face": {
        "benefit_summary": "免费账号每天有 5 分钟 ZeroGPU 配额，可运行使用共享高显存 GPU 的 Space。",
        "best_for": "短时间体验图像、音频和生成式 AI Demo。",
        "action_label": "查看 ZeroGPU 指南",
        "action_url": "https://huggingface.co/docs/hub/main/spaces-zerogpu",
        "usage_steps": [
            "注册或登录 Hugging Face。",
            "打开一个标有 ZeroGPU 的 Space。",
            "按页面说明运行 GPU 功能；繁忙时需要排队。",
            "运行时间从每日配额扣除，次日恢复。",
        ],
        "caveats": [
            "免费账号每天只有 5 分钟，排队和冷启动时间会影响体验。",
            "自行托管 ZeroGPU Space 还受账号信誉和托管数量条件限制。",
        ],
    },
    "Modal": {
        "benefit_summary": "Starter 计划每月赠送 $30 云算力额度，可用于 CPU、GPU 和 Serverless 任务。",
        "best_for": "运行脚本、批处理、模型推理或短时 GPU 任务。",
        "action_label": "开始使用 Modal",
        "action_url": "https://modal.com/docs/guide",
        "usage_steps": [
            "注册 Modal 并创建 Starter 工作区。",
            "安装 Modal Python 包并在本机完成登录。",
            "按官方示例定义函数，需要 GPU 时指定 GPU 型号。",
            "运行任务，费用自动从每月 $30 免费额度中扣除。",
        ],
        "caveats": [
            "可运行多久取决于所选 CPU、GPU 型号和实际运行时间。",
            "免费额度按月恢复，使用前应在用量页面确认剩余额度。",
        ],
    },
    "Modal:grant": {
        "benefit_summary": "符合条件的研究生、实验室和研究人员可申请最高 $10,000 学术算力资助。",
        "best_for": "有明确研究项目、需要较大规模云算力的学术团队。",
        "action_label": "查看并申请资助",
        "action_url": "https://modal.com/pricing",
        "usage_steps": [
            "准备研究方向、预计算力用途和项目周期说明。",
            "打开 Modal 学术资助入口并提交申请。",
            "等待资格审核；获批后额度会发放到对应工作区。",
        ],
        "caveats": [
            "这不是注册即送，需要提交申请并通过审核。",
            "最终额度和适用范围以 Modal 审批结果为准。",
        ],
    },
    "Lightning AI": {
        "benefit_summary": "Free 计划每月赠送 $15 credits，可在 Studio 中用于 CPU 或 GPU 机器。",
        "best_for": "在云端 Notebook 或 Studio 中做实验和轻量训练。",
        "action_label": "打开 Lightning Studios",
        "action_url": "https://lightning.ai/studios",
        "usage_steps": [
            "注册或登录 Lightning AI。",
            "创建一个 Studio，并选择所需的机器类型。",
            "启动 Notebook、训练或推理任务。",
            "在账单与用量页面监控每月 credits，任务结束后及时停止机器。",
        ],
        "caveats": [
            "GPU 时长取决于机型单价，$15 不代表固定小时数。",
            "持续运行的 Studio 会继续消耗额度，使用后要停止实例。",
        ],
    },
    "Kaggle": {
        "benefit_summary": "Kaggle Notebooks 通常每周提供约 30 小时免费 GPU，官方说明额度可能随供需上浮。",
        "best_for": "Notebook 实验、课程练习、数据竞赛和中小规模训练。",
        "action_label": "创建 Kaggle Notebook",
        "action_url": "https://www.kaggle.com/code",
        "usage_steps": [
            "注册或登录 Kaggle。",
            "创建一个新的 Notebook。",
            "在 Notebook 设置中把 Accelerator 改为 GPU。",
            "启动会话并运行代码；不用时关闭会话以节省周额度。",
        ],
        "caveats": [
            "GPU 型号和可用性由平台分配，不能保证每次相同。",
            "每周额度可能随供需变化，准确剩余时间以 Notebook 页面为准。",
        ],
    },
    "Google Colab": {
        "benefit_summary": "免费使用托管 Notebook，并有机会连接 GPU 或 TPU；资源型号和使用时长不保证。",
        "best_for": "临时 Notebook、教学演示和不要求稳定算力的实验。",
        "action_label": "打开 Google Colab",
        "action_url": "https://colab.research.google.com/",
        "usage_steps": [
            "登录 Google 账号并打开 Colab。",
            "新建或打开一个 Notebook。",
            "在运行时设置中选择 GPU 或 TPU 加速器。",
            "连接运行时；如果免费资源不可用，需要稍后重试或改用 CPU。",
        ],
        "caveats": [
            "免费 GPU/TPU 不保证可用，型号、时长和限制会动态变化。",
            "官方地区政策未包含中国大陆，页面会默认过滤此项。",
        ],
    },
    "SambaNova": {
        "benefit_summary": "未绑定付款方式的账号自动使用 Free Tier；官方按模型给出 RPM、RPD 和每日 Token 上限。",
        "best_for": "免费试用高速开源大模型 API，并明确控制每日请求与 Token 用量。",
        "action_label": "打开 SambaCloud",
        "action_url": "https://cloud.sambanova.ai/",
        "usage_steps": [
            "注册 SambaCloud，保持账号不绑定付款方式。",
            "创建 API Key，并在官方免费层表中选择模型。",
            "通过 OpenAI 兼容接口调用。",
            "读取响应中的限流头，避免超过 RPM、RPD 或 TPD。",
        ],
        "caveats": [
            "免费层限制按模型执行，任一 RPM、RPD 或 TPD 先达到都会限流。",
            "预览模型可能短期下架，不应作为生产依赖。",
        ],
    },
    "Mistral AI": {
        "benefit_summary": "Studio Free mode 默认开放 API，无需信用卡；用量和限速以账号控制台为准。",
        "best_for": "快速测试 Mistral 文本模型和 OpenAI 兼容 API。",
        "action_label": "打开 Mistral Studio",
        "action_url": "https://console.mistral.ai/",
        "usage_steps": [
            "注册或登录 Mistral Studio。",
            "在 API Keys 页面创建密钥。",
            "确认工作区处于 Free mode。",
            "使用官方 SDK 或兼容接口调用，并在控制台查看实际限额。",
        ],
        "caveats": [
            "官方未在该页面公布统一固定额度，不同账号显示可能不同。",
            "Free mode 仍受用量和速率限制。",
        ],
    },
    "Hugging Face Inference": {
        "benefit_summary": "免费用户每月获得 $0.10 Inference Providers credits，额度会自动用于 Hugging Face 路由请求。",
        "best_for": "用一个 Hugging Face Token 小量体验多个推理提供商。",
        "action_label": "打开 Inference Providers",
        "action_url": "https://huggingface.co/settings/inference-providers",
        "usage_steps": [
            "注册或登录 Hugging Face。",
            "创建 User Access Token。",
            "使用 InferenceClient 并通过 Hugging Face 路由目标模型。",
            "在账单页查看本月 credits 和消耗。",
        ],
        "caveats": [
            "免费用户月额度目前为 $0.10，官方明确注明可能调整。",
            "使用自带 Provider Key 时不会消耗这笔 Hugging Face credits。",
        ],
    },
    "SiliconFlow": {
        "benefit_summary": "完成实名认证后可调用平台免费模型，调用费用为 0；固定限速按具体模型展示。",
        "best_for": "中国大陆开发者试用文本、嵌入、重排和部分多模态 API。",
        "action_label": "打开模型广场",
        "action_url": "https://cloud.siliconflow.cn/models",
        "usage_steps": [
            "注册 SiliconFlow 并完成实名认证。",
            "在模型广场选择未带 Pro/ 前缀的免费模型。",
            "创建 API Key 后按官方接口调用。",
            "在模型详情中查看该模型固定 Rate Limits。",
        ],
        "caveats": [
            "必须实名认证后才能使用全部免费模型。",
            "免费模型固定限额因模型而异，官方总览未公布统一额度。",
        ],
    },
    "Alibaba Model Studio": {
        "benefit_summary": "首次开通百炼后，各参与模型通常各有 100 万 Token、90 天有效的一次性新人额度。",
        "best_for": "在中国大陆测试通义及百炼模型 API。",
        "action_label": "打开百炼免费额度",
        "action_url": "https://bailian.console.aliyun.com/?tab=model#/model-market/free-quota",
        "usage_steps": [
            "在华北 2（北京）地域首次开通阿里云百炼。",
            "在免费额度页确认具体模型的额度与到期日。",
            "开启“免费额度用完即停”，再创建 API Key 调用。",
            "持续查看剩余额度，避免过期或耗尽后的按量费用。",
        ],
        "caveats": [
            "这是 90 天一次性新人额度，不会重置或补发。",
            "已认证账号默认可能在额度耗尽后继续扣费，应主动开启用完即停。",
        ],
    },
    "Cerebras": {
        "benefit_summary": "添加已验证付款方式后获得 $5 credits，30 天到期；不是周期性永久免费层。",
        "best_for": "短期评估 Cerebras 高速推理 API。",
        "action_label": "打开 Cerebras Cloud",
        "action_url": "https://cloud.cerebras.ai/",
        "usage_steps": [
            "注册 Cerebras Cloud。",
            "添加并验证付款方式以激活 Free Trial。",
            "创建 API Key，并在 30 天内使用 $5 credits。",
            "额度用完后停止；只有主动购买 credits 才会继续。",
        ],
        "caveats": [
            "必须验证付款方式，未验证时 Playground 和 API 不可用。",
            "官方明确没有永久免费层，$5 credits 在 30 天后失效。",
        ],
    },
    "Baseten": {
        "benefit_summary": "新账号有未公布金额的实验 credits；正式服务按 Model API Token 或 GPU 分钟计费。",
        "best_for": "试用预优化 Model API 或部署自定义 GPU 推理。",
        "action_label": "打开 Baseten",
        "action_url": "https://app.baseten.co/",
        "usage_steps": [
            "注册 Baseten 并在账号内确认新用户 credits。",
            "选择 Model API 或 GPU 实例。",
            "调用前核对每百万 Token 或每分钟 GPU 单价。",
            "实验结束后检查 credits 与账单。",
        ],
        "caveats": [
            "官方确认有新账号 credits，但没有公开固定金额。",
            "credits 用尽后按公开价格计费，不属于永久免费层。",
        ],
    },
}


def official_guide(provider: str, offer_type: str) -> dict[str, Any]:
    """Return presentation guidance derived from the verified provider policy."""
    key = f"{provider}:grant" if offer_type == "grant" else provider
    return dict(OFFICIAL_GUIDES.get(key, {}))

__all__ = ["OFFICIAL_GUIDES", "SOURCE_BY_ID", "SOURCES", "official_guide"]
