"""Stable public facade for the deterministic AI Resource Radar core."""

__version__ = "0.7.2"

from ai_resource_radar.interfaces.http import ApiResponse, RadarDashboardPort

from ai_resource_radar.doctor import DoctorCheck, DoctorReport, diagnose, run_doctor
from ai_resource_radar.locks import (
    OperationLock,
    OperationLockedError,
    operation_lock,
    operation_lock_status,
)
from ai_resource_radar.model_registry import (
    IMAGE_MODELS,
    ImageModelSpec,
    find_image_model,
    get_image_model,
)
from ai_resource_radar.poster import (
    OpenAIImageGenerator,
    OpenClawImageGenerator,
    configure_poster,
    daily_report_status,
    generate_daily_poster,
    latest_daily_report,
    list_daily_reports,
    list_poster_models,
    poster_benchmark_status,
    poster_configuration,
    review_poster_benchmark,
    resolve_daily_poster,
    run_poster_benchmark,
    test_poster_model,
)
from ai_resource_radar.pricing import list_gpu_prices, list_token_prices
from ai_resource_radar.provider_profiles import (
    COMMUNITY_SOURCE_IDS,
    OFFICIAL_SOURCE_IDS,
    PROVIDER_BY_ALIAS,
    PROVIDER_BY_SLUG,
    PROVIDER_BY_SOURCE_ID,
    PROVIDER_PROFILES,
    ProviderProfile,
    get_provider_profile,
    integration_public_rows,
    provider_for_record,
    provider_public_rows,
    provider_slug_for,
    render_integration_snippets,
)
from ai_resource_radar.runtime import RefreshReport, refresh
from ai_resource_radar.service import backup_database
from ai_resource_radar.sources import (
    OfferObservation,
    RadarSource,
    SOURCES,
    normalize_modalities,
    resolve_modalities,
)
from ai_resource_radar.store import (
    SCHEMA_VERSION,
    UnsupportedSchemaError,
    list_changes,
    list_offers,
    radar_summary,
    source_freshness_status,
)
from ai_resource_radar.tips import (
    OFFICIAL_TIP_SOURCES,
    TIP_CATEGORIES,
    add_tip,
    approve_tip_batch,
    get_tip,
    list_tip_applications,
    list_tip_application_batches,
    list_tips,
    prune_tips,
    refresh_official_tips,
    review_tip,
    rollback_tip_batch,
    rollback_tip_application,
    seed_initial_tips,
    tips_summary,
)
from ai_resource_radar.interfaces.cli import CliContext, run_cli

# Concise host-facing alias; the original name remains public and compatible.
summary = radar_summary

__all__ = [
    "__version__",
    "SCHEMA_VERSION",
    "ApiResponse",
    "RadarDashboardPort",
    "CliContext",
    "UnsupportedSchemaError",
    "DoctorCheck",
    "DoctorReport",
    "IMAGE_MODELS",
    "ImageModelSpec",
    "OfferObservation",
    "COMMUNITY_SOURCE_IDS",
    "OFFICIAL_SOURCE_IDS",
    "PROVIDER_BY_ALIAS",
    "PROVIDER_BY_SLUG",
    "PROVIDER_BY_SOURCE_ID",
    "PROVIDER_PROFILES",
    "ProviderProfile",
    "OpenAIImageGenerator",
    "OpenClawImageGenerator",
    "OperationLock",
    "OperationLockedError",
    "RadarSource",
    "RefreshReport",
    "SOURCES",
    "diagnose",
    "backup_database",
    "configure_poster",
    "daily_report_status",
    "find_image_model",
    "get_provider_profile",
    "generate_daily_poster",
    "get_image_model",
    "latest_daily_report",
    "list_changes",
    "list_daily_reports",
    "list_gpu_prices",
    "list_offers",
    "list_token_prices",
    "integration_public_rows",
    "list_poster_models",
    "poster_benchmark_status",
    "normalize_modalities",
    "operation_lock",
    "operation_lock_status",
    "poster_configuration",
    "provider_for_record",
    "provider_public_rows",
    "provider_slug_for",
    "review_poster_benchmark",
    "radar_summary",
    "refresh",
    "resolve_modalities",
    "run_doctor",
    "run_cli",
    "source_freshness_status",
    "summary",
    "test_poster_model",
    "resolve_daily_poster",
    "run_poster_benchmark",
    "render_integration_snippets",
    "OFFICIAL_TIP_SOURCES",
    "TIP_CATEGORIES",
    "add_tip",
    "approve_tip_batch",
    "get_tip",
    "list_tip_applications",
    "list_tip_application_batches",
    "list_tips",
    "prune_tips",
    "refresh_official_tips",
    "review_tip",
    "rollback_tip_batch",
    "rollback_tip_application",
    "seed_initial_tips",
    "tips_summary",
]
